name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - release/*/*
      - feature/*
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - release/*/*
      - feature/*

jobs:
  build_and_deploy_job:
    env:
      DIST_PATH: src/samples/Uno.Themes.WinUI.Samples.Wasm/bin/Release/net9.0/dist

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    container: 'unoplatform/wasm-build:3.0'
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for gitversion
          submodules: true

      - name: Setup dotnet 9.0.300
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '9.0.300'

      - uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72 # v0.4.2
        id: nbgv
        with:
          toolVersion: 3.6.139
          setAllVars: true
    
      - run: |
          cd src/samples/WinUI/Uno.Themes.WinUI.Samples.Wasm
          dotnet publish -c Release "/p:PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}" /p:TargetFrameworkOverride=net9.0

      - uses: actions/upload-artifact@v4
        with:
          name: wasm-site
          path: ${{ env.DIST_PATH }}

      - name: Publish to Azure Static WebApps
        if: ${{ github.ref != 'refs/heads/release/prod' }}
        continue-on-error: true
        id: builddeploy_uno
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "${{ env.DIST_PATH }}" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          action: "close"
